name: 🔄 Auto-Update Multi-Sports

on:
  schedule:
    # Toutes les 2 heures, 24h/24
    - cron: '0 */2 * * *'
  
  # Permettre déclenchement manuel
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: 🔄 Auto-update tous sports
        run: |
          echo "🚀 Démarrage auto-update multi-sports..."
          echo "⏰ $(date)"
          
          response=$(curl -s -w "%{http_code}" \
            -X POST "${{ secrets.VERCEL_URL }}/api/cron/auto-update" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json")
          
          http_code="${response: -3}"
          body="${response%???}"
          
          if [ "$http_code" -eq 200 ]; then
            echo "✅ Auto-update réussi !"
            echo "$body" | jq '.'
          else
            echo "❌ Erreur auto-update (HTTP $http_code)"
            echo "$body"
            exit 1
          fi
          
      - name: 📊 Résumé
        run: |
          echo "🎯 Auto-update multi-sports terminé"
          echo "📅 $(date)"
          echo "🏆 Vérification : Football, Basketball, MMA, Rugby, F1"
          echo "⏰ Prochaine exécution : dans 2 heures"